#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for utils/mb
#
# IDENTIFICATION
#    src/agtm/utils/mb/Makefile
#
#-------------------------------------------------------------------------

subdir = src/agtm/utils/mb
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = encnames.o conv.o mbutils.o wchar.o wstrcmp.o wstrncmp.o

include $(top_srcdir)/src/agtm/common.mk

#clean distclean maintainer-clean:
#	$(MAKE) -C conversion_procs $@
