#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for utils/hash
#
# IDENTIFICATION
#    src/adbmgrd/utils/hash/Makefile
#
#-------------------------------------------------------------------------

subdir = src/adbmgrd/utils/hash
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = dynahash.o hashfn.o

include $(top_srcdir)/src/adbmgrd/common.mk
