#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for utils/resowner
#
# IDENTIFICATION
#    src/agtm/utils/resowner/Makefile
#
#-------------------------------------------------------------------------

subdir = src/agtm/utils/resowner
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = resowner.o

include $(top_srcdir)/src/agtm/common.mk
