#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for rewrite
#
# IDENTIFICATION
#    src/agtm/rewrite/Makefile
#
#-------------------------------------------------------------------------

subdir = src/agtm/rewrite
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = rewriteRemove.o rewriteDefine.o \
       rewriteHandler.o rewriteManip.o rewriteSupport.o

include $(top_srcdir)/src/agtm/common.mk
