#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for storage/buffer
#
# IDENTIFICATION
#    src/adbmgrd/storage/buffer/Makefile
#
#-------------------------------------------------------------------------

subdir = src/adbmgrd/storage/buffer
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = buf_table.o buf_init.o bufmgr.o freelist.o localbuf.o

include $(top_srcdir)/src/adbmgrd/common.mk
