#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for lib (miscellaneous stuff)
#
# IDENTIFICATION
#    src/adbmgrd/lib/Makefile
#
#-------------------------------------------------------------------------

subdir = src/adbmgrd/lib
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = ilist.o binaryheap.o stringinfo.o

include $(top_srcdir)/src/adbmgrd/common.mk
