#
# Makefile for optimizer
#
# src/adbmgrd/optimizer/Makefile
#

subdir = src/adbmgrd/optimizer
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS     = geqo path plan prep util

include $(top_srcdir)/src/adbmgrd/common.mk
