#undef NO_ENUM_A_Expr_Kind
#undef NO_ENUM_TableLikeOption
#undef NO_ENUM_DefElemAction
#undef NO_ENUM_LockClauseStrength
#undef NO_ENUM_RTEKind
#undef NO_ENUM_SetOperation
#undef NO_ENUM_ObjectType
#undef NO_ENUM_DropBehavior
#undef NO_ENUM_AlterTableType
#undef NO_ENUM_GrantTargetType
#undef NO_ENUM_GrantObjectType
#undef NO_ENUM_VariableSetKind
#undef NO_ENUM_ConstrType
#undef NO_ENUM_RoleStmtType
#undef NO_ENUM_FetchDirection
#undef NO_ENUM_FunctionParameterMode
#undef NO_ENUM_TransactionStmtKind
#undef NO_ENUM_VacuumOption
#undef NO_ENUM_DiscardMode
