#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for main
#
# IDENTIFICATION
#    src/agtm/main/Makefile
#
#-------------------------------------------------------------------------

subdir = src/agtm/main
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = agtm_sequence.o agtm_transaction.o agtm_utils.o agtm_process.o main.o

include $(top_srcdir)/src/agtm/common.mk
