#
# Makefile for the access methods module
#
# src/adbmgrd/access/Makefile
#

subdir = src/adbmgrd/access
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS	    = common gin gist hash heap index nbtree rmgrdesc spgist transam

include $(top_srcdir)/src/adbmgrd/common.mk
