#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for utils/cache
#
# IDENTIFICATION
#    src/adbmgrd/utils/cache/Makefile
#
#-------------------------------------------------------------------------

subdir = src/adbmgrd/utils/cache
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = attoptcache.o catcache.o evtcache.o inval.o plancache.o relcache.o \
	relmapper.o spccache.o syscache.o lsyscache.o typcache.o ts_cache.o

include $(top_srcdir)/src/adbmgrd/common.mk
