#
# Makefile for the rmgr descriptor routines
#
# src/adbmgrd/access/rmgrdesc/Makefile
#

subdir = src/adbmgrd/access/rmgrdesc
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = clogdesc.o dbasedesc.o gindesc.o gistdesc.o hashdesc.o heapdesc.o \
	   mxactdesc.o nbtdesc.o relmapdesc.o seqdesc.o smgrdesc.o spgdesc.o \
	   standbydesc.o tblspcdesc.o xactdesc.o xlogdesc.o pgxcdesc.o

include $(top_srcdir)/src/adbmgrd/common.mk
