#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/index
#
# IDENTIFICATION
#    src/adbmgrd/access/index/Makefile
#
#-------------------------------------------------------------------------

subdir = src/adbmgrd/access/index
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = genam.o indexam.o

include $(top_srcdir)/src/adbmgrd/common.mk
