#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for storage/large_object
#
# IDENTIFICATION
#    src/adbmgrd/storage/large_object/Makefile
#
#-------------------------------------------------------------------------

subdir = src/adbmgrd/storage/large_object
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = inv_api.o

include $(top_srcdir)/src/adbmgrd/common.mk
