#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for utils/hash
#
# IDENTIFICATION
#    src/agtm/utils/hash/Makefile
#
#-------------------------------------------------------------------------

subdir = src/agtm/utils/hash
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = dynahash.o hashfn.o

include $(top_srcdir)/src/agtm/common.mk
