#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for foreign
#
# IDENTIFICATION
#    src/agtm/foreign/Makefile
#
#-------------------------------------------------------------------------

subdir = src/agtm/foreign
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS= foreign.o

include $(top_srcdir)/src/agtm/common.mk
