#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for foreign
#
# IDENTIFICATION
#    src/adbmgrd/foreign/Makefile
#
#-------------------------------------------------------------------------

subdir = src/adbmgrd/foreign
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS= foreign.o

include $(top_srcdir)/src/adbmgrd/common.mk
