#
# Makefile for optimizer
#
# src/agtm/optimizer/Makefile
#

subdir = src/agtm/optimizer
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS     = geqo path plan prep util

include $(top_srcdir)/src/agtm/common.mk
