#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/heap
#
# IDENTIFICATION
#    src/agtm/access/heap/Makefile
#
#-------------------------------------------------------------------------

subdir = src/agtm/access/heap
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = heapam.o hio.o pruneheap.o rewriteheap.o syncscan.o tuptoaster.o visibilitymap.o

include $(top_srcdir)/src/agtm/common.mk
