#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for agtm/nodes
#
# IDENTIFICATION
#    src/agtm/nodes/Makefile
#
#-------------------------------------------------------------------------

subdir = src/agtm/nodes
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = nodeFuncs.o nodes.o list.o bitmapset.o tidbitmap.o \
       copyfuncs.o equalfuncs.o makefuncs.o \
       outfuncs.o readfuncs.o print.o read.o params.o value.o \
       outobject.o

include $(top_srcdir)/src/agtm/common.mk
