#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for utils/mmgr
#
# IDENTIFICATION
#    src/agtm/utils/mmgr/Makefile
#
#-------------------------------------------------------------------------

subdir = src/agtm/utils/mmgr
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = aset.o mcxt.o portalmem.o

include $(top_srcdir)/src/agtm/common.mk
