#include "postgres.h"

#include "parser/scanner.h"
#include "nodes/pg_list.h"
#include "nodes/parsenodes.h"
#include "nodes/value.h"
#include "mgr_gram.h"

#define PG_KEYWORD(a,b,c) {a,b,c},

const ScanKeyword ManagerKeywords[] = {
PG_KEYWORD("add", ADD_P, UNRESERVED_KEYWORD)
PG_KEYWORD("agent", AGENT, UNRESERVED_KEYWORD)
PG_KEYWORD("all", ALL, UNRESERVED_KEYWORD)
PG_KEYWORD("alter", ALTER, UNRESERVED_KEYWORD)
PG_KEYWORD("append", APPEND, UNRESERVED_KEYWORD)
PG_KEYWORD("config", CONFIG, UNRESERVED_KEYWORD)
PG_KEYWORD("coordinator", COORDINATOR, UNRESERVED_KEYWORD)
PG_KEYWORD("datanode", DATANODE, UNRESERVED_KEYWORD)
PG_KEYWORD("deploy", DEPLOY, UNRESERVED_KEYWORD)
PG_KEYWORD("drop", DROP, UNRESERVED_KEYWORD)
PG_KEYWORD("exists", EXISTS, UNRESERVED_KEYWORD)
PG_KEYWORD("f", F, UNRESERVED_KEYWORD)
PG_KEYWORD("failover", FAILOVER, UNRESERVED_KEYWORD)
PG_KEYWORD("false", FALSE_P, RESERVED_KEYWORD)
PG_KEYWORD("fast", FAST, UNRESERVED_KEYWORD)
PG_KEYWORD("get_agtm_node_topology", GET_AGTM_NODE_TOPOLOGY, UNRESERVED_KEYWORD)
PG_KEYWORD("get_all_nodename_in_spec_host", GET_ALL_NODENAME_IN_SPEC_HOST, UNRESERVED_KEYWORD)
PG_KEYWORD("get_cluster_fouritem", GET_CLUSTER_FOURITEM, UNRESERVED_KEYWORD)
PG_KEYWORD("get_cluster_headpage_line", GET_CLUSTER_HEADPAGE_LINE, UNRESERVED_KEYWORD)
PG_KEYWORD("get_cluster_summary", GET_CLUSTER_SUMMARY, UNRESERVED_KEYWORD)
PG_KEYWORD("get_coordinator_node_topology", GET_COORDINATOR_NODE_TOPOLOGY, UNRESERVED_KEYWORD)
PG_KEYWORD("get_database_summary", GET_DATABASE_SUMMARY, UNRESERVED_KEYWORD)
PG_KEYWORD("get_database_tps_qps", GET_DATABASE_TPS_QPS, UNRESERVED_KEYWORD)
PG_KEYWORD("get_database_tps_qps_interval_time", GET_DATABASE_TPS_QPS_INTERVAL_TIME, UNRESERVED_KEYWORD)
PG_KEYWORD("get_datanode_node_topology", GET_DATANODE_NODE_TOPOLOGY, UNRESERVED_KEYWORD)
PG_KEYWORD("get_host_history_usage", GET_HOST_HISTORY_USAGE, UNRESERVED_KEYWORD)
PG_KEYWORD("get_host_list_all", GET_HOST_LIST_ALL, UNRESERVED_KEYWORD)
PG_KEYWORD("get_host_list_spec", GET_HOST_LIST_SPEC, UNRESERVED_KEYWORD)
PG_KEYWORD("get_slowlog", GET_SLOWLOG, UNRESERVED_KEYWORD)
PG_KEYWORD("get_threshold_all_type", GET_THRESHOLD_ALL_TYPE, UNRESERVED_KEYWORD)
PG_KEYWORD("get_threshold_type", GET_THRESHOLD_TYPE, UNRESERVED_KEYWORD)
PG_KEYWORD("gtm", GTM, UNRESERVED_KEYWORD)
PG_KEYWORD("host", HOST, UNRESERVED_KEYWORD)
PG_KEYWORD("i", I, UNRESERVED_KEYWORD)
PG_KEYWORD("if", IF_P, UNRESERVED_KEYWORD)
PG_KEYWORD("immediate", IMMEDIATE, UNRESERVED_KEYWORD)
PG_KEYWORD("init", INIT, UNRESERVED_KEYWORD)
PG_KEYWORD("list", LIST, UNRESERVED_KEYWORD)
PG_KEYWORD("master", MASTER, UNRESERVED_KEYWORD)
PG_KEYWORD("mode", MODE, UNRESERVED_KEYWORD)
PG_KEYWORD("monitor", MONITOR, UNRESERVED_KEYWORD)
PG_KEYWORD("node", NODE, UNRESERVED_KEYWORD)
PG_KEYWORD("not", NOT, RESERVED_KEYWORD)
PG_KEYWORD("off", OFF, UNRESERVED_KEYWORD)
PG_KEYWORD("on", ON, UNRESERVED_KEYWORD)
PG_KEYWORD("parm", PARM, UNRESERVED_KEYWORD)
PG_KEYWORD("password", PASSWORD, UNRESERVED_KEYWORD)
PG_KEYWORD("s", S, UNRESERVED_KEYWORD)
PG_KEYWORD("set", SET, UNRESERVED_KEYWORD)
PG_KEYWORD("slave", SLAVE, UNRESERVED_KEYWORD)
PG_KEYWORD("smart", SMART, UNRESERVED_KEYWORD)
PG_KEYWORD("start", START, UNRESERVED_KEYWORD)
PG_KEYWORD("stop", STOP, UNRESERVED_KEYWORD)
PG_KEYWORD("true", TRUE_P, RESERVED_KEYWORD)
PG_KEYWORD("to", TO, UNRESERVED_KEYWORD)
PG_KEYWORD("update_critical_value", UPDATE_CRITICAL_VALUE, UNRESERVED_KEYWORD)
PG_KEYWORD("update_emergency_value", UPDATE_EMERGENCY_VALUE, UNRESERVED_KEYWORD)
PG_KEYWORD("update_warning_value", UPDATE_WARNING_VALUE, UNRESERVED_KEYWORD)
};

const int NumManagerKeywords = lengthof(ManagerKeywords);
