#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for port/darwin
#
# IDENTIFICATION
#    src/agtm/port/darwin/Makefile
#
#-------------------------------------------------------------------------

subdir = src/agtm/port/darwin
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = system.o

include $(top_srcdir)/src/agtm/common.mk
