#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for optimizer/prep
#
# IDENTIFICATION
#    src/adbmgrd/optimizer/prep/Makefile
#
#-------------------------------------------------------------------------

subdir = src/adbmgrd/optimizer/prep
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = prepjointree.o prepqual.o preptlist.o prepunion.o

include $(top_srcdir)/src/adbmgrd/common.mk
