#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for storage/smgr
#
# IDENTIFICATION
#    src/agtm/storage/smgr/Makefile
#
#-------------------------------------------------------------------------

subdir = src/agtm/storage/smgr
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = md.o smgr.o smgrtype.o

include $(top_srcdir)/src/agtm/common.mk
