#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for utils/error
#
# IDENTIFICATION
#    src/agtm/utils/error/Makefile
#
#-------------------------------------------------------------------------

subdir = src/agtm/utils/error
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = assert.o elog.o

include $(top_srcdir)/src/agtm/common.mk
