#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for lib (miscellaneous stuff)
#
# IDENTIFICATION
#    src/agtm/lib/Makefile
#
#-------------------------------------------------------------------------

subdir = src/agtm/lib
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = ilist.o binaryheap.o stringinfo.o

include $(top_srcdir)/src/agtm/common.mk
