#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/gin
#
# IDENTIFICATION
#    src/adbmgrd/access/gin/Makefile
#
#-------------------------------------------------------------------------

subdir = src/adbmgrd/access/gin
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = ginutil.o gininsert.o ginxlog.o ginentrypage.o gindatapage.o \
	ginbtree.o ginscan.o ginget.o ginvacuum.o ginarrayproc.o \
	ginbulk.o ginfast.o

include $(top_srcdir)/src/adbmgrd/common.mk
