#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for utils/init
#
# IDENTIFICATION
#    src/adbmgrd/utils/init/Makefile
#
#-------------------------------------------------------------------------

subdir = src/adbmgrd/utils/init
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = globals.o miscinit.o postinit.o

include $(top_srcdir)/src/adbmgrd/common.mk
