#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for utils/time
#
# IDENTIFICATION
#    src/adbmgrd/utils/time/Makefile
#
#-------------------------------------------------------------------------

subdir = src/adbmgrd/utils/time
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = combocid.o tqual.o snapmgr.o

include $(top_srcdir)/src/adbmgrd/common.mk
