#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for storage/freespace
#
# IDENTIFICATION
#    src/adbmgrd/storage/freespace/Makefile
#
#-------------------------------------------------------------------------

subdir = src/adbmgrd/storage/freespace
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = freespace.o fsmpage.o indexfsm.o

include $(top_srcdir)/src/adbmgrd/common.mk
