#
# Makefile for the storage manager subsystem
#
# src/agtm/storage/Makefile
#

subdir = src/agtm/storage
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS     = buffer file freespace ipc large_object lmgr page smgr

include $(top_srcdir)/src/agtm/common.mk
