#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for storage/file
#
# IDENTIFICATION
#    src/agtm/storage/file/Makefile
#
#-------------------------------------------------------------------------

subdir = src/agtm/storage/file
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = fd.o buffile.o copydir.o reinit.o

include $(top_srcdir)/src/agtm/common.mk
