#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for main
#
# IDENTIFICATION
#    src/adbmgrd/main/Makefile
#
#-------------------------------------------------------------------------

subdir = src/adbmgrd/main
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = main.o

include $(top_srcdir)/src/adbmgrd/common.mk
