#
# Makefile for the storage manager subsystem
#
# src/adbmgrd/storage/Makefile
#

subdir = src/adbmgrd/storage
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS     = buffer file freespace ipc large_object lmgr page smgr

include $(top_srcdir)/src/adbmgrd/common.mk
