#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/common
#
# IDENTIFICATION
#    src/adbmgrd/access/common/Makefile
#
#-------------------------------------------------------------------------

subdir = src/adbmgrd/access/common
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = heaptuple.o indextuple.o printtup.o reloptions.o scankey.o \
	tupconvert.o tupdesc.o

include $(top_srcdir)/src/adbmgrd/common.mk
